server:
  port: 20002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tea_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    sentinel:
          transport:
            dashboard: localhost:8089
            port: 8722
          eager: true
          log:
            dir: ./logs/sentinel

# ========== Sentinel 流量控制与熔断降级配置 ==========